### PR TITLE
Feature: Allow resolving DNS with CLASH itself , bugs fix & more clear use logic

### PR DESCRIPTION
**Pull request by vernesong**

### CODE REVIEW

**Comment by frainzy1477** [comment]
i tested your changes but have some issues so i decided to use what was necessary. For example, getting config from sub link cannot resolve. Thanks anyway and let me know if you tested and everything was working.

**Comment by vernesong** [comment]
# Resolving DNS with CLASH itself when users do not choose to use PDNSD service
## For making sure  DNS settings in config.yml are correct, or should do something like below what could work normally on myself router. When users choose to use PDNSD service, it is not neccesary to change the DNS servers settings in  config.yml , because all DNS resolving were done with  PDNSD service.

### file:inid.d/clash
```shell
yml_change(){
	...
grep dns: /etc/clash/config.yml
if [ "$?" -ne "0" ]; then
     sed -i "/Proxy:/i\dns:" /etc/clash/config.yml
     sed -i "/dns:/a\  enable: true" /etc/clash/config.yml
     sed -i "/enable: true/a\  ipv6: false" /etc/clash/config.yml
     sed -i "/ipv6: false/a\  listen: 0.0.0.0:7874" /etc/clash/config.yml
     sed -i "/listen: 0.0.0.0:7874/a\  enhanced-mode: redir-host" /etc/clash/config.yml
     sed -i "/enhanced-mode: redir-host/a\  nameserver:" /etc/clash/config.yml
     sed -i "/nameserver:/a\  - 114.114.114.114" /etc/clash/config.yml
     sed -i "/114.114.114.114/a\  - 119.29.29.29" /etc/clash/config.yml
     sed -i "/119.29.29.29/a\  - 223.5.5.5" /etc/clash/config.yml
     sed -i "/223.5.5.5/a\  fallback:" /etc/clash/config.yml
     sed -i "/fallback:/a\  - tls://dns.rubyfish.cn:853" /etc/clash/config.yml
     sed -i "/dns.rubyfish.cn:853/a\  - tls://1.1.1.1:853" /etc/clash/config.yml
     sed -i "/1.1.1.1:853/a\  - tcp://208.67.222.222:443" /etc/clash/config.yml
     sed -i "/208.67.222.222:443/a\  - tls://dns.google" /etc/clash/config.yml
 else
     if [ $dns -ne 1 ];  then
        sed -i -e '/nameserver:/p' -e '/Proxy:/p' -e '/nameserver:/,/Proxy:/d' /etc/clash/config.yml
        sed -i "/nameserver:/a\  - 114.114.114.114" /etc/clash/config.yml
        sed -i "/114.114.114.114/a\  - 119.29.29.29" /etc/clash/config.yml
        sed -i "/119.29.29.29/a\  - 223.5.5.5" /etc/clash/config.yml
        sed -i "/223.5.5.5/a\  fallback:" /etc/clash/config.yml
        sed -i "/fallback:/a\  - tls://dns.rubyfish.cn:853" /etc/clash/config.yml
        sed -i "/dns.rubyfish.cn:853/a\  - tls://1.1.1.1:853" /etc/clash/config.yml
        sed -i "/1.1.1.1:853/a\  - tcp://208.67.222.222:443" /etc/clash/config.yml
        sed -i "/208.67.222.222:443/a\  - tls://dns.google" /etc/clash/config.yml
     fi
fi
   ...
 }

yml_dns_change(){

	if [ $dns -ne 1 ];  then
	   dns_port=`grep listen: /etc/clash/config.yml |awk -F ':' '{print $3}' |tr -cd "[0-9]"`
	   if [ $dns_port -eq 53 ]; then
	      sed -i '/listen:/ d' /etc/clash/config.yml
              sed -i "/nameserver:/i\  listen: 0.0.0.0:7874" /etc/clash/config.yml
	      uci del dhcp.@dnsmasq[-1].server
	      uci add_list dhcp.@dnsmasq[0].server=127.0.0.1#7874
	      uci delete dhcp.@dnsmasq[0].resolvfile
	      uci set dhcp.@dnsmasq[0].noresolv=1
	      uci commit dhcp
	   else
	      uci del dhcp.@dnsmasq[-1].server
	      uci add_list dhcp.@dnsmasq[0].server=127.0.0.1#$dns_port
	      uci delete dhcp.@dnsmasq[0].resolvfile
	      uci set dhcp.@dnsmasq[0].noresolv=1
	      uci commit dhcp
	   fi
       fi
}

**Comment by vernesong** [comment]
# Explain for changes

  [`[ $(uci get clash.config.auto_update 0) -eq 1 ] && echo "0 $(uci get clash.config.auto_update_time) * * * /usr/share/clash/clash.sh" >> $CRON_FILE`](https://github.com/frainzy1477/clash/blob/9de7b310bc6849200f92fa2233474a0d27b41d64/luci-app-clash/root/etc/init.d/clash#L232)

## It is not work for me except like this below
```shell
[ $(uci get clash.config.auto_update) -eq 1 ] && echo "0 $(uci get clash.config.auto_update_time) * * * /usr/share/clash/clash.sh" >> $CRON_FILE
```
## In my opinions, if allow to resolve DNS with CLASH itself, it is not neccesary to add a port option for chinese DNS resolving. And the oversea  port option can used to identification DNS resolving, it is neccesary for users to change the DNS servers to more [Non-standard port DNS servers](https://ilpl.me/2018/08/17/public-DNS-5353-list/).  Anyway, we can get the same info from "Dns Fowarder" option what used for PDNSD work. So I changed some codes with [clash.po](https://github.com/frainzy1477/clash/pull/5/commits/b563079e066eb4b1690fc8229dbbf19b6c04fc71), [dns.lua](https://github.com/frainzy1477/clash/pull/5/commits/89de1911db254c328752d780870d87916a185466) and [inid.d/clash](https://github.com/frainzy1477/clash/pull/5/commits/87e0be3e07c48b28b65b98241f909ebc0887501b) for more clear use logic.
```shell
pdnsd_genconfig() {
...
  pdnsd_listen_port2=$(uci get clash.config.dns_server_d |awk -F '#' '{print $2}' 2>/dev/null)

global {
    perm_cache=1024;        
    cache_dir="/var/dnscache";     
    pid_file = /var/run/dnscache.pid;
    server_ip = 0.0.0.0;        
    server_port=$pdnsd_listen_port2;           
    status_ctl = on;
    paranoid=on;                  
    query_method=udp_only;      
    neg_domain_pol = off;  
    par_queries = 400;          
    min_ttl = 1h;               
    max_ttl = 1w;               
    timeout = 10;               
}

...
}

start_pdnsd() {
   pdnsd_listen_port1=$(uci get clash.config.dns_server |awk -F '#' '{print $2}' 2>/dev/null)
...
global {
	perm_cache=1024;
	cache_dir="/var/pdnsd";
	pid_file = /var/run/pdnsd.pid;
	run_as="nobody";
	server_ip = 0.0.0.0;
	server_port = $pdnsd_listen_port1;
	status_ctl = on;
	query_method = tcp_only;
	min_ttl=1h;
	max_ttl=1w;
	timeout=20;
	neg_domain_pol=on;
	proc_limit=2;
	procq_limit=8;
}

...
	
}
```
## Because many browsers blocking request to HTTP resources from a HTTPS website, so add a button for someone who could not use the local dashboard. 
For examples:
[http://clash.razord.top/#/proxies](http://clash.razord.top/#/proxies)
[http://yacd.haishan.me/#/](http://yacd.haishan.me/#/)

## End with some translation-changes

**Comment by frainzy1477** [comment]
OK, tested your latest commit and is working fine now

**Pull request closed without merging**
